import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Box } from '@mui/material'
import TopImg from '../public/img/Image.png'

export default function Home() {
  return (
    <div>
      <Head>
        <title>My-page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Image
        src={TopImg}
        sx={{ width: '100vw', height:'auto' }} 
      /> */}
      <Box sx={{ backgroundImage: `url(${TopImg.src})`, width: "100vw", height: "100vh", backgroundPosition: "no-repeat", backgroundSize: "cover" }}></Box>
    </div>
  )
}
